### ISSUE TITLE
Updating python-primesieve-feedstock to the latest version

### ISSUE THREAD

**Issue by kimwalisch** [conda-forge/python-primesieve-feedstock#9]
Hi,

I have updated primesieve-python to version 1.3.0 and there are some significant changes:

1) The primesieve-python modules do not link anymore against libprimesieve (.a/.so/.dylib).  Instead the primesieve-python modules include the primesieve C/C++ sources files. This change was needed to support OpenMP multi-threading. I don't think this has any implications though for python-primesieve-feedstock.

2) If my understanding is correct then updating python-primesieve-feedstock to the latest primesieve-python is as easy as updating ```recipe/meta.yaml``` to ```
{% set version = "1.3.0" %}```.

3) primesieve-python contains a new backwards incompatible API:

* ```primesieve.generate_primes(n)``` -> ```primesieve.primes(n)```
* ```primesieve.numpy.generate_primes_array(n)``` -> ```primesieve.numpy.primes(n)```

I don't know how many people depend on python-primesieve-feedstock but their code will break when we update to the latest version. I hope there are very few people with this issue, but I think it is worth simplifying the primesieve-python API.

**Comment by jakirkham** [comment]
Is there a reason to call this 1.3.0 vs. 2.0.0 if there are API breaks? Asking this as I'm more use to semantic versioning practices, which would prefer the latter in this case.

**Comment by kimwalisch** [comment]
I agree 2.0.0 would have been a better version number. But when I made the breaking changes about a month ago I did not think about it.

What do you suggest: should I do a new 2.0.0 primesieve-python release or can we leave it as is? As far as I can see even if I would increment the version to 2.0.0 users would experience the same compilation issues as with version 1.3.0!?
